# Generated by Django 5.2.9 on 2026-01-12 04:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Curso / Parcial'), ('COMPLETED', 'Finalizado / Oficial')], default='IN_PROGRESS', max_length=15)),
                ('final_score_t1', models.IntegerField(default=0)),
                ('final_score_t2', models.IntegerField(default=0)),
                ('total_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('time_set', models.DurationField(blank=True, null=True)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('set_winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('coach', 'Entrenador')], default='coach', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Extern_Control_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('denomination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('micro_denomination', models.CharField(default='', max_length=150)),
                ('week_day', models.CharField(default='Lunes', max_length=10)),
                ('micro_number', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=100)),
                ('rival_team_name', models.CharField(max_length=150)),
                ('game_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('denomination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('game_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intern_Control_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('denomination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('micro_denomination', models.CharField(default='', max_length=150)),
                ('week_day', models.CharField(default='Lunes', max_length=10)),
                ('micro_number', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=100)),
                ('game_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('position', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=20)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.athlete')),
            ],
        ),
        migrations.AddField(
            model_name='game_info',
            name='set_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_set_1', to='core.set'),
        ),
        migrations.AddField(
            model_name='game_info',
            name='set_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_set_2', to='core.set'),
        ),
        migrations.AddField(
            model_name='game_info',
            name='set_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_set_3', to='core.set'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('players', models.ManyToManyField(related_name='teams', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SER', 'Servicio'), ('REC', 'Recepción'), ('ACO', 'Acomodada'), ('ATA', 'Ataque'), ('BLO', 'Bloqueo'), ('DEF', 'Defensa'), ('ENF', 'Error No Forzado')], max_length=3)),
                ('sub_action', models.CharField(blank=True, choices=[('BAJ', 'Por abajo'), ('FLO', 'Flotado'), ('SAL', 'Salto fuerte'), ('SAF', 'Salto flotado'), ('2MA', 'Dos manos abajo'), ('PPM', 'Pirámide/Puño'), ('P2A', 'Dos manos arriba'), ('P2B', 'Dos manos abajo'), ('RM', 'Remate fuerte'), ('RCA', 'Remate colocado'), ('UB', 'Usa Bloqueo'), ('TR', 'Tiro de nudillo'), ('ADC', 'Acomodada directa'), ('RD', 'Recibo directo'), ('BL', 'Línea'), ('BD', 'Diagonal'), ('BN', 'No bloquea/Cubre'), ('DD', 'Diagonal desafiando'), ('DLT', 'Hacia la línea'), ('LD', 'Línea a diagonal'), ('CC', 'Centro')], max_length=3, null=True)),
                ('evaluation', models.IntegerField(default=0, help_text='0=Negativo, 4=Positivo. Escala 0-4')),
                ('timestamp', models.CharField(help_text='Formato MM:SS', max_length=10)),
                ('origin_zone', models.CharField(blank=True, max_length=10, null=True)),
                ('target_zone', models.CharField(blank=True, max_length=10, null=True)),
                ('wind', models.CharField(blank=True, choices=[('F', 'A favor'), ('C', 'En contra')], max_length=1, null=True)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.athlete')),
                ('set_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='core.set')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_plays', to='core.team')),
            ],
        ),
        migrations.AddField(
            model_name='game_info',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_1', to='core.team'),
        ),
        migrations.AddField(
            model_name='game_info',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_2', to='core.team'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('denomination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('objective', models.CharField(max_length=200)),
                ('game_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
