# Generated by Django 5.2.9 on 2026-05-25 19:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Curso / Parcial'), ('COMPLETED', 'Finalizado / Oficial')], default='IN_PROGRESS', max_length=15)),
                ('tournament', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=30)),
                ('matchNumber', models.IntegerField(default=0)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('eventType', models.CharField(default='', max_length=50)),
                ('startTime', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('denomination', models.CharField(blank=True, max_length=200, null=True)),
                ('meso', models.CharField(blank=True, max_length=50, null=True)),
                ('micro', models.CharField(blank=True, max_length=50, null=True)),
                ('weekDay', models.CharField(blank=True, max_length=10, null=True)),
                ('microNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('objective', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, max_length=10, null=True)),
                ('createdBy', models.EmailField(blank=True, max_length=254, null=True)),
                ('pointsA', models.IntegerField(default=0)),
                ('pointsB', models.IntegerField(default=0)),
                ('setsA', models.IntegerField(default=0)),
                ('setsB', models.IntegerField(default=0)),
                ('currentSet', models.IntegerField(default=1)),
                ('totalTimeSeconds', models.IntegerField(blank=True, null=True)),
                ('realTimeSeconds', models.IntegerField(blank=True, null=True)),
                ('final_score_a', models.IntegerField(default=0)),
                ('final_score_b', models.IntegerField(default=0)),
                ('total_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('coach', 'Entrenador')], default='coach', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Intern_Control_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('meso_denomination', models.CharField(choices=[('ENT', 'Entrante'), ('BAS', 'Básico'), ('BDE', 'Básico desarrollador'), ('BES', 'Básico estabilizador'), ('PRE_CON', 'Preparatorio de control'), ('PRE_COM', 'Precompetitivo'), ('COM', 'Competitivo'), ('RES_MAN', 'De restablecimiento mantenedor'), ('PRE_RES', 'Preparatorio de restablecimiento'), ('PRE_MAN', 'Preparatorio de mantenimiento')], max_length=10)),
                ('micro_denomination', models.CharField(choices=[('ORD', 'Ordinario'), ('CHO', 'De choque intensivo'), ('APR', 'De aproximación'), ('COM', 'Competitivo'), ('REC', 'De recuperación o restablecimiento')], max_length=10)),
                ('week_day', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='Lunes', max_length=10)),
                ('micro_number', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=100)),
                ('game_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('position', models.CharField(choices=[('B', 'Bloqueador'), ('D', 'Defensor')], default='B', max_length=1)),
                ('zone', models.CharField(choices=[('IZQ', 'Izquierda'), ('CEN', 'Centro'), ('DER', 'Derecha')], default='CEN', max_length=3)),
                ('fullName', models.CharField(default='', max_length=100)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('time_set', models.DurationField(blank=True, null=True)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('set_winner', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.game_info')),
            ],
        ),
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rallies', to='core.set')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('players', models.ManyToManyField(related_name='teams', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SER', 'Servicio'), ('REC', 'Recepción'), ('ACO', 'Acomodada'), ('ATA', 'Ataque'), ('BLO', 'Bloqueo'), ('DEF', 'Defensa'), ('ENF', 'Error No Forzado')], max_length=3)),
                ('sub_action', models.CharField(blank=True, choices=[('BAJ', 'Por abajo'), ('FLO', 'Flotado'), ('SAL', 'Salto fuerte'), ('SAF', 'Salto flotado'), ('2MA', 'Dos manos abajo'), ('PPM', 'Pirámide/Puño'), ('P2A', 'Dos manos arriba'), ('P2B', 'Dos manos abajo'), ('RM', 'Remate fuerte'), ('RCA', 'Remate colocado'), ('UB', 'Usa Bloqueo'), ('TR', 'Tiro de nudillo'), ('ACD', 'Acomodada directa'), ('RDJ', 'RDJN'), ('RDP', 'RDPMP'), ('RD', 'Recibo directo'), ('BL', 'Línea'), ('BD', 'Diagonal'), ('BN', 'No bloquea/Cubre'), ('DD', 'Diagonal desafiando'), ('DLT', 'Hacia la línea'), ('LD', 'Línea a diagonal'), ('CC', 'Centro'), ('ENS', 'S'), ('ENR', 'R'), ('ENP', 'P'), ('ENM', 'M')], max_length=3, null=True)),
                ('evaluation', models.IntegerField(default=0, help_text='0=Negativo, 4=Positivo. Escala 0-4')),
                ('origin_zone', models.CharField(blank=True, max_length=3, null=True)),
                ('target_zone', models.CharField(blank=True, max_length=3, null=True)),
                ('timestamp', models.CharField(help_text='Formato MM:SS', max_length=10)),
                ('wind', models.CharField(blank=True, choices=[('F', 'A favor'), ('C', 'En contra')], max_length=1, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='core.player')),
                ('rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='core.rally')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_plays', to='core.team')),
            ],
        ),
        migrations.AddField(
            model_name='game_info',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_a', to='core.team', verbose_name='Equipo A'),
        ),
        migrations.AddField(
            model_name='game_info',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_b', to='core.team', verbose_name='Equipo B'),
        ),
        migrations.CreateModel(
            name='Extern_Control_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('meso_denomination', models.CharField(choices=[('ENT', 'Entrante'), ('BAS', 'Básico'), ('BDE', 'Básico desarrollador'), ('BES', 'Básico estabilizador'), ('PRE_CON', 'Preparatorio de control'), ('PRE_COM', 'Precompetitivo'), ('COM', 'Competitivo'), ('RES_MAN', 'De restablecimiento mantenedor'), ('PRE_RES', 'Preparatorio de restablecimiento'), ('PRE_MAN', 'Preparatorio de mantenimiento')], max_length=10)),
                ('micro_denomination', models.CharField(choices=[('ORD', 'Ordinario'), ('CHO', 'De choque intensivo'), ('APR', 'De aproximación'), ('COM', 'Competitivo'), ('REC', 'De recuperación o restablecimiento')], max_length=10)),
                ('week_day', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='Lunes', max_length=10)),
                ('micro_number', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=100)),
                ('game_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extern_team_a', to='core.team', verbose_name='Equipo A')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extern_team_b', to='core.team', verbose_name='Equipo B')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('denomination', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('game_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_team_a', to='core.team', verbose_name='Equipo A')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_team_b', to='core.team', verbose_name='Equipo B')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('meso_denomination', models.CharField(choices=[('ENT', 'Entrante'), ('BAS', 'Básico'), ('BDE', 'Básico desarrollador'), ('BES', 'Básico estabilizador'), ('PRE_CON', 'Preparatorio de control'), ('PRE_COM', 'Precompetitivo'), ('COM', 'Competitivo'), ('RES_MAN', 'De restablecimiento mantenedor'), ('PRE_RES', 'Preparatorio de restablecimiento'), ('PRE_MAN', 'Preparatorio de mantenimiento')], max_length=10)),
                ('micro_denomination', models.CharField(choices=[('ORD', 'Ordinario'), ('CHO', 'De choque intensivo'), ('APR', 'De aproximación'), ('COM', 'Competitivo'), ('REC', 'De recuperación o restablecimiento')], max_length=10)),
                ('week_day', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='Lunes', max_length=10)),
                ('micro_number', models.IntegerField(default=0)),
                ('objective', models.CharField(max_length=200)),
                ('game_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game_info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
