# Generated by Django 5.2.9 on 2026-05-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fullName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
