# Generated by Django 5.2.9 on 2026-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_play_action_type_alter_play_origin_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='origin_zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='target_zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
