# Generated by Django 5.2.9 on 2026-05-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_play_origin_zone_alter_play_target_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='action_type',
            field=models.CharField(choices=[('SERVICIO', 'Servicio'), ('RECEPCION', 'Recepción'), ('ACOMODADA', 'Acomodada'), ('ATAQUE', 'Ataque'), ('BLOQUEO', 'Bloqueo'), ('DEFENSA', 'Defensa'), ('ERRORES_SERV', 'Error de Servicio'), ('ERRORES_COM', 'Error de Comunicación'), ('ERRORES_POS', 'Error de Posicionamiento'), ('ERRORES_TEC', 'Error Técnico')], max_length=30),
        ),
        migrations.AlterField(
            model_name='play',
            name='origin_zone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='sub_action',
            field=models.CharField(blank=True, choices=[('BAJ', 'Por abajo'), ('FLO', 'Flotado'), ('SAL', 'Salto fuerte'), ('SAF', 'Salto flotado'), ('2ma', 'Dos manos abajo'), ('Ppm', 'Pirámide/Puño'), ('P2a', 'Dos manos arriba'), ('P2b', 'Dos manos abajo'), ('Rm', 'Remate fuerte'), ('Rca', 'Remate colocado'), ('Ub', 'Usa Bloqueo'), ('Tr', 'Tiro de nudillo'), ('Acd', 'Acomodada directa'), ('Rdjn', 'RDJN'), ('Rdpmp', 'RDPMP'), ('Rd', 'Recibo directo'), ('Bl', 'Línea'), ('Bd', 'Diagonal'), ('Bn', 'No bloquea/Cubre'), ('Dd', 'Diagonal desafiando'), ('Dltd', 'Hacia la línea'), ('Ld', 'Línea a diagonal'), ('Cc', 'Centro'), ('SFC', 'Saque fuera de cancha'), ('SR', 'Saque red'), ('SME', 'Saque mal ejecutado'), ('CI', 'Confusión interna'), ('MC', 'Mala comunicación'), ('NAT', 'No atento'), ('CJR', 'Caída en jugada rival'), ('MCA', 'Mala colocación anticipada'), ('JFZ', 'Jugador fuera de zona'), ('GMD', 'Golpe mal dirigido'), ('TI', 'Toque incorrecto'), ('MER', 'Mala ejecución de remate'), ('BTR', 'Bloqueo tras red')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='target_zone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='timestamp',
            field=models.CharField(help_text='Formato MM:SS o ISO', max_length=30),
        ),
        migrations.AlterField(
            model_name='play',
            name='wind',
            field=models.CharField(blank=True, choices=[('VIENTO A FAVOR', 'A favor'), ('VIENTO EN CONTRA', 'En contra')], max_length=30, null=True),
        ),
    ]
